# Generated by Django 3.2 on 2024-02-27 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lat',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='long',
            field=models.TextField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50, null=True)),
                ('dosage', models.TextField(max_length=50, null=True)),
                ('time', models.TimeField(null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
    ]
