# Generated by Django 3.2 on 2024-02-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_auto_20240227_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='acc',
            field=models.TextField(default=0, null=True),
        ),
    ]
