# Generated by Django 3.2 on 2024-03-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_patient_acc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='acc',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='long',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.TextField(max_length=20, null=True)),
                ('longitude', models.TextField(max_length=20, null=True)),
                ('accuracy', models.TextField(max_length=20, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
    ]
