# Generated by Django 3.2 on 2024-03-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_auto_20240302_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='accuracy',
        ),
    ]
