# Generated by Django 4.2.11 on 2024-06-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Patient", "0005_remove_location_accuracy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="facial_embedding",
            field=models.BinaryField(null=True),
        ),
    ]
